blank_issues_enabled: true
contact_links:
  - name: Arcalot Discussions
    url: https://github.com/arcalot/.github/discussions
    about: Provide feedback and suggestions, ask questions, and discuss with others